### ISSUE TITLE
Act. 2; Infografía Sobre el Conocimiento, Emmanuel Marx Salazar González, 1Bs

### ISSUE THREAD

**Issue by marxgonzalez29** [SistemasTecTlaxiaco/actividad-2-infografia-marxgonzalez29#1]
![IMG-20220903-WA0008](https://user-images.githubusercontent.com/112300981/188283679-093db357-41b4-435d-ba07-8694236050b4.jpg)

**Comment by Jaczibeth** [comment]
de 20% sacaste 17.5%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
